[package]
name = "Dynamic Toads"
version = "0.0.0"

[addresses]
token_objects = "0x4"
aptoads_objects = "a00d367d8a4b849cae62fb8141c034600443fa6be695a8ff6fd06245c78eccdb"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework//aptos-token-objects'