[package]
name = "Dynamic Toads"
version = "0.0.0"

[addresses]
token_objects = "0x4"
aptoads_objects = "3e3f4caea68c15a272626f7f27801044296004bbd8e1c9c0dc0b8dbf5bccfa23"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework//aptos-token-objects'